# Generated by Django 5.2.12 on 2026-03-05 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'survey_sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('dropdown', 'Dropdown'), ('checkbox', 'Checkbox'), ('radio', 'Radio'), ('textarea', 'Textarea'), ('email', 'Email')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField()),
                ('options', models.JSONField(blank=True, default=list, help_text='Options for dropdown/radio/checkbox fields')),
                ('is_encrypted', models.BooleanField(default=False)),
                ('validation_rules', models.JSONField(blank=True, default=dict, help_text='Validation rules: min, max, min_length, max_length, regex')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='surveys.section')),
            ],
            options={
                'db_table': 'survey_fields',
                'ordering': ['order'],
                'unique_together': {('section', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'surveys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='section',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='surveys.survey'),
        ),
        migrations.CreateModel(
            name='FieldDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('equals', 'Equals'), ('not_equals', 'Not Equals'), ('contains', 'Contains'), ('greater_than', 'Greater Than'), ('less_than', 'Less Than'), ('in', 'In')], max_length=20)),
                ('value', models.JSONField()),
                ('action', models.CharField(choices=[('show_options', 'Show Options'), ('hide_options', 'Hide Options'), ('set_value', 'Set Value')], max_length=20)),
                ('action_value', models.JSONField()),
                ('dependent_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='surveys.field')),
                ('depends_on_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependants', to='surveys.field')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_dependencies_direct', to='surveys.survey')),
            ],
            options={
                'verbose_name_plural': 'Field dependencies',
                'db_table': 'field_dependencies',
            },
        ),
        migrations.CreateModel(
            name='ConditionalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('equals', 'Equals'), ('not_equals', 'Not Equals'), ('contains', 'Contains'), ('greater_than', 'Greater Than'), ('less_than', 'Less Than'), ('in', 'In')], max_length=20)),
                ('value', models.JSONField()),
                ('depends_on_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependant_rules', to='surveys.field')),
                ('target_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditional_rules', to='surveys.field')),
                ('target_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditional_rules', to='surveys.section')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditional_rules_direct', to='surveys.survey')),
            ],
            options={
                'db_table': 'conditional_rules',
            },
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['status'], name='surveys_status_893a62_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['created_by'], name='surveys_created_6cc90a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('survey', 'order')},
        ),
    ]
